parameters:
#    maps_search.example.class: Maps\SearchBundle\Example

services:
#    maps_search.example:
#        class: %maps_search.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
