parameters:
#    maps_groups.example.class: Maps\GroupsBundle\Example

services:
#    maps_groups.example:
#        class: %maps_groups.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
