wg_page:
  resource: "@MapsPageBundle/Controller/PageController.php"
  type:     annotation
  prefix:   /

wg_page_admin:
  resource: "@MapsPageBundle/Controller/Admin/AdminController.php"
  type:     annotation
  prefix:   /admin
