groups:
  resource: "@MapsGroupsBundle/Controller/"
  type:     annotation

page:
  resource: "@MapsPageBundle/Controller/"
  type:     annotation

page_admin:
  resource: "@MapsPageBundle/Controller/Admin/"
  type:     annotation
