fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /admin/profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    pattern: /admin/profile/password/change
    defaults: { _controller: FOSUserBundle:ChangePassword:changePassword }
    requirements:
        _method: GET|POST

main:
    resource: "@MapsMainBundle/Controller/"
    type:     annotation

site_groups:
    resource: "@MapsGroupsBundle/Controller/"
    type:     annotation

admin_groups:
    resource: "@MapsGroupsBundle/Controller/Admin/"
    type:     annotation

page:
    resource: "@MapsPageBundle/Controller/"
    type:     annotation

page_admin:
    resource: "@MapsPageBundle/Controller/Admin/"
    type:     annotation


search_admin:
    resource: "@MapsSearchBundle/Controller/Admin/"
    type:     annotation
