parameters:
#    maps_user.example.class: Maps\UserBundle\Example

services:
#    maps_user.example:
#        class: %maps_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
