parameters:
#    maps_main.example.class: Maps\MainBundle\Example

services:
#    maps_main.example:
#        class: %maps_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
