parameters:
#    maps_page.example.class: Maps\PageBundle\Example

services:
    maps.twig.deleteform_extension:
        class: Maps\PageBundle\Twig\DeleteFormExtension
        tags:
            - { name: twig.extension }
